### ISSUE TITLE
Create go server

### ISSUE THREAD

**Issue by gmelodie** [MLH-Fellowship/FellowshipWrapup#11]
Create and deployt the backend server as well as specify the available endpoints.

**Comment by IamCathal** [comment]
Added [gmux](https://github.com/gorilla/mux) http server in https://github.com/MLH-Fellowship/FellowshipWrapup/commit/2fe678203848cb2bb3f0cd2533ecf02461ad0a8c

Seperated out the queries logic from the routing logic as it's for the better. Implementation isn't perfect but logging and serving is fine. There is a weird trick needed to serve requests for custom usernames but I'll talk about that tomorrow
