### ISSUE TITLE
Github GraphQL query caching

### ISSUE THREAD

**Issue by gmelodie** [MLH-Fellowship/FellowshipWrapup#12]
Create caching for Github API queries. The way me and @IamCathal are thinking about this is having a directory structure like so:

```.
.
├── frontend
├── backend
│   ├── main.go
│   └── util.go
├── data
│   ├── gmelodie
│   │   ├── issue.json
│   │   └── pullRequest.json
│   └── IamCathal
│       ├── issue.json
│       └── pullRequest.json
└── README.md
```

If a user is found under `data`, don't make the API calls again.

**Comment by sebastiancrossa** [comment]
This is an interesting idea. Let's try to make it work.

**Comment by IamCathal** [comment]
Caching of data was implemented in https://github.com/MLH-Fellowship/FellowshipWrapup/pull/16
