### ISSUE TITLE
Connect template to use placeholder data through a json file

### ISSUE THREAD

**Issue by kartikcho** [MLH-Fellowship/FellowshipWrapup#4]
Currently the template uses static data with `{ }` to depict where placeholder data should be inserted.

This issue would be marked successful when,
- [ ] JSON placeholder file is used to insert data onto the template
- [ ] A proper structure is defined in the placeholder JSON file to direct how the generated profile should look like from the backend
- [ ] Nothing breaks 🦀

**Comment by IamCathal** [comment]
Getting the data into a standard JSON format for the frontend won't be a problem at all once we have it so this shouldn't be too much of a task thankfully.

**Comment by kartikcho** [comment]
Can the frontend team get a placeholder format? If you have a specific architecture in mind, it'll help write the relevant JS for displaying data, otherwise we'd have to refactor a bit.

**Comment by IamCathal** [comment]
@kartikcho Pushed a PR with the basic JSON format in the `data` on `new-queries` branch
