### ISSUE TITLE
JSON file definition

### ISSUE THREAD

**Issue by gmelodie** [MLH-Fellowship/FellowshipWrapup#8]
Define basic data the JSON file needs.

**Comment by gmelodie** [comment]
Here are the numbers I think would be good to have (please add any other needed)

- [ ] Number of PRs opened by fellow
  - [ ] Merged
  - [ ] Not merged
- [ ]  Number of issues opened by fellow
  - [ ] Now closed
  - [ ] Still open
- [ ] Number of lines of code wrote by fellow
- [ ] Number of commits done by fellow
- [ ] Number of issues and PRs fellow participated in
- [ ] Number of people "touched" by fellow

**Comment by IamCathal** [comment]
Breakdown of languages of the repos that they contributed to

**Comment by gmelodie** [comment]
@IamCathal could you give further info on how that would actually be structured into the JSON format?

**Comment by kartikcho** [comment]
Should we show statistics of "not merged"? I think it sounds negative, instead we could do something like,

- Total PRs opened
- PRs merged

Nothing major, just sounds better and also could be displayed in a pie chart format or something.

**Comment by sebastiancrossa** [comment]
I was thinking, could we also get the name (or number) of the pod the user was in, alongside some basic info (name + GH profile pic) of the fellows from that pod?

It would be awesome if we could have a section where all of the other fellows were displayed too.

**Comment by kartikcho** [comment]
Good idea, we could look into how [Fellowbook](https://github.com/MLH-Fellowship/0.2.1-fellowbook) does it.
